CREATE TABLE CLIENTE(
	CI VARCHAR(500),
	NOMBRE VARCHAR(30),
	APELLIDO VARCHAR(30),
	FECHA_NAC DATE,
	CONSTRAINT CI PRIMARY KEY (CI)
);

CREATE TABLE TARJETA(
	N_TDC VARCHAR(16),
	COD_SEG VARCHAR(3),
	LIMITE_CRED DECIMAL(22,6),
	FECHA_EXP DATE,
	FECHA_EMI DATE,
	CRED_DISP DECIMAL(22,6),
	SALDO DECIMAL(22,6),
	CI VARCHAR(500),
	CONSTRAINT N_TDC PRIMARY KEY (N_TDC),
	CONSTRAINT FK_CI FOREIGN KEY (CI) REFERENCES CLIENTE (CI)
);

CREATE TABLE TRANSACCION(
	N_TRANS INT NOT NULL AUTO_INCREMENT,
	N_TDC VARCHAR(16),
	CI VARCHAR(500),
	FECHA_TRANS DATE,
	MONTO DECIMAL(22,6),
	COD_OPERACION VARCHAR(3),
	CONSTRAINT TRANSACCION PRIMARY KEY (N_TRANS),
	CONSTRAINT FK_N_TDC FOREIGN KEY (N_TDC) REFERENCES TARJETA (N_TDC),
	CONSTRAINT FK_CI FOREIGN KEY (CI) REFERENCES CLIENTE (CI)
);